version: '3'

services:
  softether:
    image: toprock/softether
    cap_add:
      - NET_ADMIN
    restart: always
    ports:
      - 5555:5555
      - 5555:5555/udp
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "./softether_data:/mnt"
      - "./softether_log:/root/server_log"
      - "./softether_packetlog:/root/packet_log"
      - "./softether_securitylog:/root/security_log"
